### ISSUE TITLE
Relicense to BSD-3-Clause OR Apache-2.0

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hexml#15]
I would like to relicense this package to BSD-3-Clause OR Apache-2.0, as described at https://neilmitchell.blogspot.com/2018/08/licensing-my-haskell-packages.html

There have been two tiny (but most welcome!) contributions to this repo:

* @chrisdone did 22923b55ca7390f1973ddfd0d0e517f13cf8a8a4
* @dbeacham did 22923b55ca7390f1973ddfd0d0e517f13cf8a8a4

If you object to the relicensing and feel your changes gain you copyright on the project please say!

**Comment by chrisdone** [comment]
No objection.

**Comment by ndmitchell** [comment]
Done.
