### ISSUE TITLE
compile errors / inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [ndmitchell/hexml#5]
Hi,

I gave hexml a test-drive, and found the following meta-data inaccuracies:

----

 `base >= 4.5` is needed

counter-example with GHC 7.2.2 (base-4.4)

```
Configuring component lib from hexml-0.1
Preprocessing library hexml-0.1...
[1 of 1] Compiling Text.XML.Hexml   ( src/Text/XML/Hexml.hs, /tmp/hexml-0.1/dist-newstyle/build/x86_64-linux/ghc-7.2.2/hexml-0.1/build/Text/XML/Hexml.o )

src/Text/XML/Hexml.hs:86:20:
    Not in scope: `<>'
    Perhaps you meant one of these:
      `<$>' (imported from Control.Applicative),
      `<*>' (imported from Control.Applicative),
      `>>' (imported from Prelude)
```

----

`extra >= 0.3` is needed

counter-example with `extra-0.2`:

```
Configuring component lib from hexml-0.1
Preprocessing library hexml-0.1...
[1 of 1] Compiling Text.XML.Hexml   ( src/Text/XML/Hexml.hs, /tmp/hexml-0.1/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hexml-0.1/build/Text/XML/Hexml.o )

src/Text/XML/Hexml.hs:151:33:
    Not in scope: `&&&'
    Perhaps you meant `&&' (imported from Prelude)
```

----

The lower-bound for `bytestring` couldn't be verified as the solver wasn't able to access older bytestring versions than the one bundled with GHC 7.4.2

**Comment by ndmitchell** [comment]
Thanks for the info. I'll update the bounds and make a fresh release.

**Comment by hvr** [comment]
Btw, as far as hexml-0.1 is concerned, I went ahead and fixed up the meta-data already: http://hackage.haskell.org/package/hexml-0.1/revisions/

**Comment by ndmitchell** [comment]
Data updated - there'll be a new release tonight. Thanks for all your work to curate/inform/educate/fix these version bounds!
